# Generated by Django 3.2.5 on 2021-07-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False, verbose_name='finished')),
                ('link', models.URLField(max_length=1024, verbose_name='link_encuesta')),
                ('name', models.CharField(max_length=100, verbose_name='nombre_encuesta')),
                ('avg_duration', models.FloatField(default=5.0, verbose_name='duracion_promedio')),
                ('prize', models.CharField(default='', max_length=200, verbose_name='premio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha_de_creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha_ultima_actualizacion')),
            ],
        ),
    ]
